name: cinemapedia_220512
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.4
  card_swiper: ^3.0.1
  intl: ^0.20.2
  animate_do: ^4.2.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icon/
    - assets/audio/
    - assets/animations/

# Configuraci√≥n de iconos de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/LogoCineVerse.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/LogoCineVerse.png"
  windows:
    generate: true
    image_path: "assets/icon/LogoCineVerse.png"
  macos:
    generate: true
    image_path: "assets/icon/LogoCineVerse.png"
  linux:
    generate: true
    image_path: "assets/icon/LogoCineVerse.png"
